### PR TITLE
Fix 'SelectionList screens with Enter keybind for selection action results in shrug guy dialog. #2094'

### LINKED ISSUE #2094: SelectionList screens with Enter keybind for selection action results in shrug guy dialog.
**Describe the bug**
SelectionList screens with Enter keybind for selection action results in shrug guy dialog because the call to the selection action during keybind fails to pass in the selected index in the action payload.

**To Reproduce**
1. Go to screen that uses SelectionListUIMessage
2. Make sure the selection action has a keybind
3. Arrow down on selection list
4. Click Enter
5. See shrug guy
6. 
**Screenshots**
selection-list-shrug-guy
Screen Shot 2022-03-15 at 3 19 35 PM

### PR DESCRIPTION
**Pull request by stojankz**
update to send the action payload for all the selection buttons

### Issues Fixed
Closes #2094 

selection-list-shrug-guy-fix

### CODE REVIEW

File: openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/generic-selection-list-screen.ts [hunk 1]
```diff
@@ -79,6 +79,18 @@ export class GenericSelectionListScreenDirective<T extends SelectableItemInterfa
                     this.index = this.screen.selectionList.indexOf(this.selectedItem);
                 }
             }
+
+            if (this.screen.selectionButtons) {
+                this.screen.selectionButtons.forEach(button => {
+                    this.actionService.registerActionPayload(button.action, () => {
```
Comment (jrmihalick) [inline openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/generic-selection-list-screen.ts:85]: Should you also unregister the payloads on the component destroy?

**Review by jrmihalick — DISMISSED** [review]

File: openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/generic-selection-list-screen.ts [hunk 2]
```diff
@@ -79,6 +80,18 @@ export class GenericSelectionListScreenDirective<T extends SelectableItemInterfa
...
+                        if (this.screen.multiSelect) {
```
Comment (jchirico8) [inline openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/generic-selection-list-screen.ts:87]: You can turn this into a ternary operator and remove all of the braces `this.screen.multiSelect ? this.indexes...`

**Review by jrmihalick — APPROVED** [review]

**Review by jrmihalick — DISMISSED** [review]

**Review by jchirico8 — DISMISSED** [review]

**Review by jchirico8 — APPROVED** [review]
