### PR TITLE
Set a timeout on stream reads from the zpl port connection

### LINKED ISSUE #2013: Timeout required for Zebra Printer Status Connection
**Describe the bug**
The default timeout of the ZQ320 is around 6 seconds. Change the status timeout to match that of the SocketConnectionFactory timeouts.

### PR DESCRIPTION
**Pull request by liambell-le**
### Issues Fixed
#2013

### CODE REVIEW

File: openpos-peripheral/src/main/java/org/jumpmind/pos/print/ZebraPrinter.java [hunk 1]
```diff
@@ -243,7 +243,7 @@ public int readPrinterStatus() {
             try {
                 connection.open();
                 com.zebra.sdk.printer.ZebraPrinter printer = ZebraPrinterFactory.getInstance(connection);
-
+                printer.getConnection().setMaxTimeoutForRead(2500);
```
Comment (chenson42) [inline openpos-peripheral/src/main/java/org/jumpmind/pos/print/ZebraPrinter.java:246]: look in the socket connection factory.  there is an example of getting the timeout from settings
