### PR TITLE
Fixed: #2457 - Add openpos config for SymDS externalId

### LINKED ISSUE #2457: Allow SymmetricDS externalId to be configured separately from the openpos installationId
Allow SymmetricDS externalId to be configured separately from the openpos installationId.

New parameter added:
 - openpos.externalId

### PR DESCRIPTION
**Pull request by gwilmer**
### Issues Fixed
#2457

### CODE REVIEW

File: openpos-symds/src/main/java/org/jumpmind/pos/symds/DefaultSymDSConfigurator.java [hunk 1]
```diff
@@ -23,6 +23,10 @@ public class DefaultSymDSConfigurator implements ISymDSConfigurator {
     @Value("${openpos.installationId:'not set'}")
     String installationId;
 
+    @Value("${openpos.externalId:not set}")
```
Comment (chenson42) [inline openpos-symds/src/main/java/org/jumpmind/pos/symds/DefaultSymDSConfigurator.java:26]: I think this should be openops.symmetric.externalId

**Review by chenson42 — APPROVED** [review]
